/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/pdeslaur/kube-pat/pkg/apis/portaddresstranslation/v1beta1"
	scheme "github.com/pdeslaur/kube-pat/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PortAddressTranslationsGetter has a method to return a PortAddressTranslationInterface.
// A group's client should implement this interface.
type PortAddressTranslationsGetter interface {
	PortAddressTranslations(namespace string) PortAddressTranslationInterface
}

// PortAddressTranslationInterface has methods to work with PortAddressTranslation resources.
type PortAddressTranslationInterface interface {
	Create(*v1beta1.PortAddressTranslation) (*v1beta1.PortAddressTranslation, error)
	Update(*v1beta1.PortAddressTranslation) (*v1beta1.PortAddressTranslation, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.PortAddressTranslation, error)
	List(opts v1.ListOptions) (*v1beta1.PortAddressTranslationList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.PortAddressTranslation, err error)
	PortAddressTranslationExpansion
}

// portAddressTranslations implements PortAddressTranslationInterface
type portAddressTranslations struct {
	client rest.Interface
	ns     string
}

// newPortAddressTranslations returns a PortAddressTranslations
func newPortAddressTranslations(c *K8sV1beta1Client, namespace string) *portAddressTranslations {
	return &portAddressTranslations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the portAddressTranslation, and returns the corresponding portAddressTranslation object, and an error if there is any.
func (c *portAddressTranslations) Get(name string, options v1.GetOptions) (result *v1beta1.PortAddressTranslation, err error) {
	result = &v1beta1.PortAddressTranslation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("portaddresstranslations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PortAddressTranslations that match those selectors.
func (c *portAddressTranslations) List(opts v1.ListOptions) (result *v1beta1.PortAddressTranslationList, err error) {
	result = &v1beta1.PortAddressTranslationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("portaddresstranslations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested portAddressTranslations.
func (c *portAddressTranslations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("portaddresstranslations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a portAddressTranslation and creates it.  Returns the server's representation of the portAddressTranslation, and an error, if there is any.
func (c *portAddressTranslations) Create(portAddressTranslation *v1beta1.PortAddressTranslation) (result *v1beta1.PortAddressTranslation, err error) {
	result = &v1beta1.PortAddressTranslation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("portaddresstranslations").
		Body(portAddressTranslation).
		Do().
		Into(result)
	return
}

// Update takes the representation of a portAddressTranslation and updates it. Returns the server's representation of the portAddressTranslation, and an error, if there is any.
func (c *portAddressTranslations) Update(portAddressTranslation *v1beta1.PortAddressTranslation) (result *v1beta1.PortAddressTranslation, err error) {
	result = &v1beta1.PortAddressTranslation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("portaddresstranslations").
		Name(portAddressTranslation.Name).
		Body(portAddressTranslation).
		Do().
		Into(result)
	return
}

// Delete takes name of the portAddressTranslation and deletes it. Returns an error if one occurs.
func (c *portAddressTranslations) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("portaddresstranslations").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *portAddressTranslations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("portaddresstranslations").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched portAddressTranslation.
func (c *portAddressTranslations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.PortAddressTranslation, err error) {
	result = &v1beta1.PortAddressTranslation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("portaddresstranslations").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
