---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: portaddresstranslations.k8s.deslauriers.io
spec:
  group: k8s.deslauriers.io
  version: v1beta1
  scope: Namespaced
  names:
    plural: portaddresstranslations
    singular: portaddresstranslation
    kind: PortAddressTranslation
    shortNames:
    - pat

---

apiVersion: v1
kind: Namespace
metadata:
  name: kube-pat

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-pat
  namespace: kube-pat
spec:
  replicas: 4
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: kube-pat
  template:
    metadata:
      labels:
        app: kube-pat
    spec:
      containers:
      - name: kube-pat
        image: github.com/pdeslaur/kube-pat/cmd/forwarder
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 10m
            memory: 10Mi

---

kind: Service
apiVersion: v1
metadata:
  name: kube-pat-tcp
  namespace: kube-pat
spec:
  selector:
    app: kube-pat
  ports:
  - name: keepalive
    protocol: TCP
    port: 8080
  type: LoadBalancer

---

kind: Service
apiVersion: v1
metadata:
  name: kube-pat-udp
  namespace: kube-pat
spec:
  selector:
    app: kube-pat
  ports:
  - name: keepalive
    protocol: UDP
    port: 8080
  type: LoadBalancer
